org: ctbrown5
app: writey-drawey-app
service: writey-drawey-offline

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev

functions:
  gameApi:
    handler: ./index.update
    timeout: 3
    events:
      - http:
          method: POST
          path: /api
          cors: true
  getState:
    handler: ./index.get
    events:
      - http:
          path: /state
          method: GET
          cors: true
  getCompletedGames:
    handler: ./index.getCompletedGames
    events:
      - http:
          path: '/completed-games'
          method: GET
          cors: true
